name: 'vansah-action'
description: 'GitHub action to import test results into "Vansah for Jira" - A complete Test Management tool for Jira.'
author: 'Testpoint'
inputs:
  vansahToken:
    required: true
    description: 'Provide a unique vansah token to submit the reports'
  testFormat:
    required: false
    description: 'Provide valid format such as "TestNg, Junit, Nunit"'
  testPaths:
    required: true
    description: 'Provide Test Report Path'
  Issue_TestFolders:
    required: true
    description: 'Provide cycle information'
  comment:
    required: true
    description: 'Provide comment'
  
outputs:
  out:
    description: 'Will Output the Message on success/failure'
runs:
  using: 'node16'
  main: 'dist/index.js'
