name: 'vansah-action'
description: 'GitHub action to import test results into "Vansah for Jira" - A complete Test Management tool for Jira.'
author: 'Testpoint'
inputs:
  vansahConnectToken:
    required: true
    description: 'Provide a Vansah Connect Token'
  testFormat:
    required: true
    description: "Provide valid format 'TESTNG' "
    default: "TESTNG"
  testPaths:
    required: true
    description: 'Provide Test Report Path'
  
outputs:
  out:
    description: 'Will Output the Message on success/failure'
runs:
  using: 'node16'
  main: 'dist/index.js'
