name: VansahAPI Regression v3
on:
  workflow_dispatch:
  push:
    branches:
      - main
       
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # INstall Node on the runner
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '12.x'
    
    # Install Run
    - name: Run the Actions
      run: |
       npm install 
       node index.js
      
